# Generated by Django 4.1 on 2022-08-21 10:25

from django.db import migrations, models

import apps.users.services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profilemodel_bound_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=apps.users.services.upload_picture_to),
        ),
    ]
