# Generated by Django 4.1 on 2022-08-21 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientmodel_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
