# Generated by Django 4.1 on 2022-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patientmodel_patients_patientmodel_patient'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='patients',
            field=models.ManyToManyField(related_name='patients', to='patients.patientmodel'),
        ),
    ]
